### ISSUE TITLE
add 'delete' action

### ISSUE THREAD

**Issue by vchepkov** [puppetlabs/puppetlabs-puppet_conf#29]
add 'delete' action to remove a setting
```
USAGE: puppet config delete [--section SECTION_NAME] (<setting>

Deletes a setting from the specified section. (The default is the section 'main').
```

**Comment by david22swan** [comment]
Associated PR has been raised by @fetzerms and has since been merged so I'll be closing this issue.
Thank you again for the work you've done :)
